schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "iocgpoly_lip_sync_2d"
version = "1.0.0"
name = "Lip Sync 2D"
tagline = "Addon to easily add mouth sprites to your models"
maintainer = "Charley 3D <charley@cgpoly.io>"
# Supported types: "add-on", "theme"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
# website = "https://extensions.blender.org/add-ons/my-example-package/"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
# tags = ["Animation", "Sequencer"]

blender_version_min = "4.4.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
# # Optional: required by some licenses.
# copyright = [
#   "2002-2024 Developer Name",
#   "1998 Company Name",
# ]

# # Optional: list of supported platforms. If omitted, the extension will be available in all operating systems.
# platforms = ["windows-x64", "macos-arm64", "linux-x64"]
# # Other supported platforms: "windows-arm64", "macos-x64"

# # Optional: bundle 3rd party Python modules.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
platforms = ["windows-arm64","windows-x64", "macos-x64", "macos-arm64", "linux-x64"]
wheels = ["./wheels/typing_extensions-4.13.2-py3-none-any.whl", "./wheels/pyparsing-3.2.3-py3-none-any.whl", "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl", "./wheels/urllib3-2.4.0-py3-none-any.whl", "./wheels/joblib-1.4.2-py3-none-any.whl", "./wheels/csvw-3.5.1-py2.py3-none-any.whl", "./wheels/rpds_py-0.24.0-cp311-cp311-win_amd64.whl", "./wheels/dlinfo-2.0.0-py3-none-any.whl", "./wheels/attrs-25.3.0-py3-none-any.whl", "./wheels/segments-2.3.0-py2.py3-none-any.whl", "./wheels/jsonschema_specifications-2024.10.1-py3-none-any.whl", "./wheels/language_tags-1.2.0-py3-none-any.whl", "./wheels/referencing-0.36.2-py3-none-any.whl", "./wheels/requests-2.32.3-py3-none-any.whl", "./wheels/rfc3986-1.5.0-py2.py3-none-any.whl", "./wheels/jsonschema-4.23.0-py3-none-any.whl", "./wheels/certifi-2025.1.31-py3-none-any.whl", "./wheels/six-1.17.0-py2.py3-none-any.whl", "./wheels/charset_normalizer-3.4.1-cp311-cp311-win_amd64.whl", "./wheels/isodate-0.7.2-py3-none-any.whl", "./wheels/rdflib-7.1.4-py3-none-any.whl", "./wheels/uritemplate-4.1.1-py2.py3-none-any.whl", "./wheels/phonemizer-3.3.0-py3-none-any.whl", "./wheels/idna-3.10-py3-none-any.whl", "./wheels/regex-2024.11.6-cp311-cp311-win_amd64.whl", "./wheels/babel-2.17.0-py3-none-any.whl", "./wheels/colorama-0.4.6-py2.py3-none-any.whl", "./wheels/macos/urllib3-2.4.0-py3-none-any.whl", "./wheels/macos/charset_normalizer-3.4.1-cp310-cp310-macosx_10_9_universal2.whl", "./wheels/macos/vosk-0.3.41-py3-none-macosx_10_6_universal2.whl", "./wheels/macos/rpds_py-0.24.0-cp311-cp311-macosx_10_12_x86_64.whl", "./wheels/macos/requests-2.32.3-py3-none-any.whl", "./wheels/macos/certifi-2025.1.31-py3-none-any.whl", "./wheels/macos/regex-2024.11.6-cp311-cp311-macosx_10_9_universal2.whl", "./wheels/macos/pycparser-2.22-py3-none-any.whl", "./wheels/macos/tqdm-4.67.1-py3-none-any.whl", "./wheels/macos/idna-3.10-py3-none-any.whl", "./wheels/macos/rpds_py-0.24.0-cp311-cp311-macosx_11_0_arm64.whl", "./wheels/macos/cffi-1.17.1-cp311-cp311-macosx_11_0_arm64.whl", "./wheels/macos/colorama-0.4.6-py2.py3-none-any.whl", "./wheels/linux/urllib3-2.4.0-py3-none-any.whl", "./wheels/linux/charset_normalizer-3.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", "./wheels/linux/cffi-1.17.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", "./wheels/linux/requests-2.32.3-py3-none-any.whl", "./wheels/linux/certifi-2025.1.31-py3-none-any.whl", "./wheels/linux/srt-3.5.3-py3-none-any.whl", "./wheels/linux/pycparser-2.22-py3-none-any.whl", "./wheels/linux/tqdm-4.67.1-py3-none-any.whl", "./wheels/linux/idna-3.10-py3-none-any.whl", "./wheels/linux/websockets-15.0.1-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl", "./wheels/linux/vosk-0.3.45-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl", "./wheels/windows/urllib3-2.4.0-py3-none-any.whl", "./wheels/windows/vosk-0.3.41-py3-none-win_amd64.whl", "./wheels/windows/cffi-1.17.1-cp311-cp311-win_amd64.whl", "./wheels/windows/requests-2.32.3-py3-none-any.whl", "./wheels/windows/certifi-2025.1.31-py3-none-any.whl", "./wheels/windows/charset_normalizer-3.4.1-cp311-cp311-win_amd64.whl", "./wheels/windows/pycparser-2.22-py3-none-any.whl", "./wheels/windows/tqdm-4.67.1-py3-none-any.whl", "./wheels/windows/idna-3.10-py3-none-any.whl", "./wheels/windows/colorama-0.4.6-py2.py3-none-any.whl"]

# # Optional: add-ons can list which resources they will require:
# # * files (for access of any filesystem operations)
# # * network (for internet access)
# # * clipboard (to read and/or write the system clipboard)
# # * camera (to capture photos and videos)
# # * microphone (to capture audio)
# #
# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #
# # For each permission it is important to also specify the reason why it is required.
# # Keep this a single short sentence without a period (.) at the end.
# # For longer explanations use the documentation or detail page.
#
# [permissions]
 network = "Need to download Voices Models to enable lip sync"
 files = "Import Models / Extract libs to disk"
# clipboard = "Copy and paste bone transforms"

# # Optional: advanced build settings.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# # These are the default build excluded patterns.
# # You only need to edit them if you want different options.
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]
