schema_version = "1.0.0"
id = "iocgpoly_lip_sync"
version = "1.0.3"
name = "Lip Sync"
tagline = "Automatic lip sync for your Blender models"
maintainer = "Charley 3D <charley@cgpoly.fr>"
type = "add-on"
website = "https://github.com/Charley3d/lip-sync"
tags = ["Animation", "Sequencer"]
blender_version_min = "4.4.0"
license = [
  "SPDX:GPL-3.0-or-later",
]
platforms = ["windows-x64", "macos-x64", "macos-arm64", "linux-x64"]
wheels = ["./wheels/common/attrs-25.3.0-py3-none-any.whl", "./wheels/common/babel-2.17.0-py3-none-any.whl", "./wheels/common/csvw-3.5.1-py2.py3-none-any.whl", "./wheels/common/isodate-0.7.2-py3-none-any.whl", "./wheels/common/joblib-1.4.2-py3-none-any.whl", "./wheels/common/jsonschema-4.23.0-py3-none-any.whl", "./wheels/common/jsonschema_specifications-2024.10.1-py3-none-any.whl", "./wheels/common/language_tags-1.2.0-py3-none-any.whl", "./wheels/common/phonemizer-3.3.0-py3-none-any.whl", "./wheels/common/python_dateutil-2.9.0.post0-py2.py3-none-any.whl", "./wheels/common/rdflib-7.1.4-py3-none-any.whl", "./wheels/common/referencing-0.36.2-py3-none-any.whl", "./wheels/common/rfc3986-1.5.0-py2.py3-none-any.whl", "./wheels/common/segments-2.3.0-py2.py3-none-any.whl", "./wheels/common/six-1.17.0-py2.py3-none-any.whl", "./wheels/common/tqdm-4.67.1-py3-none-any.whl", "./wheels/common/typing_extensions-4.13.2-py3-none-any.whl", "./wheels/common/uritemplate-4.1.1-py2.py3-none-any.whl", "./wheels/linux/cffi-1.17.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", "./wheels/linux/charset_normalizer-3.4.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", "./wheels/linux/regex-2024.11.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", "./wheels/linux/rpds_py-0.24.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", "./wheels/linux/vosk-0.3.41-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl", "./wheels/macos/cffi-1.17.1-cp311-cp311-macosx_11_0_arm64.whl", "./wheels/macos/charset_normalizer-3.4.1-cp310-cp310-macosx_10_9_universal2.whl", "./wheels/macos/regex-2024.11.6-cp311-cp311-macosx_10_9_universal2.whl", "./wheels/macos/rpds_py-0.24.0-cp311-cp311-macosx_10_12_x86_64.whl", "./wheels/macos/rpds_py-0.24.0-cp311-cp311-macosx_11_0_arm64.whl", "./wheels/macos/vosk-0.3.41-py3-none-macosx_10_6_universal2.whl", "./wheels/windows/cffi-1.17.1-cp311-cp311-win_amd64.whl", "./wheels/windows/regex-2024.11.6-cp311-cp311-win_amd64.whl", "./wheels/windows/rpds_py-0.24.0-cp311-cp311-win_amd64.whl", "./wheels/windows/vosk-0.3.41-py3-none-win_amd64.whl"]
[permissions]
 network = "Need to download Voices Models to enable lip sync"
 files = "Import Models / Extract libs to disk"
[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "dev_tools.py",
  "/.idea/",
  "/.venv/",
  "/.venv311/",
]
