schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "iocgpoly_lip_sync"
version = "1.0.2"
name = "Lip Sync"
tagline = "Automatic lip sync for your Blender models"
maintainer = "Charley 3D <charley@cgpoly.fr>"
# Supported types: "add-on", "theme"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
website = "https://github.com/Charley3d/lip-sync"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Animation", "Sequencer"]

blender_version_min = "4.4.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
# # Optional: required by some licenses.
# copyright = [
#   "2002-2024 Developer Name",
#   "1998 Company Name",
# ]

# # Optional: list of supported platforms. If omitted, the extension will be available in all operating systems.
# platforms = ["windows-x64", "macos-arm64", "linux-x64"]
# # Other supported platforms: "windows-arm64", "macos-x64"

# # Optional: bundle 3rd party Python modules.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
platforms = ["windows-arm64","windows-x64", "macos-x64", "macos-arm64", "linux-x64"]
wheels = ["./wheels/common/attrs-25.3.0-py3-none-any.whl", "./wheels/common/babel-2.17.0-py3-none-any.whl", "./wheels/common/certifi-2025.1.31-py3-none-any.whl", "./wheels/common/charset_normalizer-3.4.1-cp311-cp311-win_amd64.whl", "./wheels/common/colorama-0.4.6-py2.py3-none-any.whl", "./wheels/common/csvw-3.5.1-py2.py3-none-any.whl", "./wheels/common/dlinfo-2.0.0-py3-none-any.whl", "./wheels/common/idna-3.10-py3-none-any.whl", "./wheels/common/isodate-0.7.2-py3-none-any.whl", "./wheels/common/joblib-1.4.2-py3-none-any.whl", "./wheels/common/jsonschema-4.23.0-py3-none-any.whl", "./wheels/common/jsonschema_specifications-2024.10.1-py3-none-any.whl", "./wheels/common/language_tags-1.2.0-py3-none-any.whl", "./wheels/common/phonemizer-3.3.0-py3-none-any.whl", "./wheels/common/pycparser-2.22-py3-none-any.whl", "./wheels/common/pyparsing-3.2.3-py3-none-any.whl", "./wheels/common/python_dateutil-2.9.0.post0-py2.py3-none-any.whl", "./wheels/common/rdflib-7.1.4-py3-none-any.whl", "./wheels/common/referencing-0.36.2-py3-none-any.whl", "./wheels/common/regex-2024.11.6-cp311-cp311-win_amd64.whl", "./wheels/common/requests-2.32.3-py3-none-any.whl", "./wheels/common/rfc3986-1.5.0-py2.py3-none-any.whl", "./wheels/common/rpds_py-0.24.0-cp311-cp311-win_amd64.whl", "./wheels/common/segments-2.3.0-py2.py3-none-any.whl", "./wheels/common/six-1.17.0-py2.py3-none-any.whl", "./wheels/common/tqdm-4.67.1-py3-none-any.whl", "./wheels/common/typing_extensions-4.13.2-py3-none-any.whl", "./wheels/common/uritemplate-4.1.1-py2.py3-none-any.whl", "./wheels/common/urllib3-2.4.0-py3-none-any.whl", "./wheels/linux/cffi-1.17.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", "./wheels/linux/charset_normalizer-3.4.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", "./wheels/linux/regex-2024.11.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", "./wheels/linux/rpds_py-0.24.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", "./wheels/linux/vosk-0.3.41-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl", "./wheels/macos/cffi-1.17.1-cp311-cp311-macosx_11_0_arm64.whl", "./wheels/macos/charset_normalizer-3.4.1-cp310-cp310-macosx_10_9_universal2.whl", "./wheels/macos/regex-2024.11.6-cp311-cp311-macosx_10_9_universal2.whl", "./wheels/macos/rpds_py-0.24.0-cp311-cp311-macosx_10_12_x86_64.whl", "./wheels/macos/rpds_py-0.24.0-cp311-cp311-macosx_11_0_arm64.whl", "./wheels/macos/vosk-0.3.41-py3-none-macosx_10_6_universal2.whl", "./wheels/windows/cffi-1.17.1-cp311-cp311-win_amd64.whl", "./wheels/windows/vosk-0.3.41-py3-none-win_amd64.whl"]

# # Optional: add-ons can list which resources they will require:
# # * files (for access of any filesystem operations)
# # * network (for internet access)
# # * clipboard (to read and/or write the system clipboard)
# # * camera (to capture photos and videos)
# # * microphone (to capture audio)
# #
# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #
# # For each permission it is important to also specify the reason why it is required.
# # Keep this a single short sentence without a period (.) at the end.
# # For longer explanations use the documentation or detail page.
#
[permissions]
 network = "Need to download Voices Models to enable lip sync"
 files = "Import Models / Extract libs to disk"
# clipboard = "Copy and paste bone transforms"

# # Optional: advanced build settings.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
[build]
# # These are the default build excluded patterns.
# # You only need to edit them if you want different options.
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "dev_tools.py",
  "/.idea/",
  "/.venv/",
  "/.venv311/",
]
