name: Build eSpeak NG for Linux (Ubuntu 18.04)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf \
            automake \
            libtool \
            pkg-config \
            libpcaudio-dev \
            libsonic-dev \
            libespeak-ng-dev \
            portaudio19-dev \
            git libasound2-dev

      # Step 3: Clone the eSpeak NG repository
      - name: Clone eSpeak NG
        run: git clone --depth 1 https://github.com/espeak-ng/espeak-ng.git

      # Step 4: Build eSpeak NG
      - name: Build eSpeak NG
        working-directory: espeak-ng
        run: |
          ./autogen.sh
          ./configure --prefix=$PWD/../build --enable-shared --disable-static
          make -j$(nproc)
          make install

      # Step 5: Upload the built binaries
      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: espeak-ng-linux
          path: ./build/bin/
