name: Simple Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build-extension:
      name: Blender Extension Build
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Install Blender via Snap
          run: sudo snap install blender --classic

        - name: Build Extension with blender
          run: blender --command extension build

        - name: Get generated zip filename
          id: get-zip
          run: echo "ZIP_NAME=$(basename $(ls ./*.zip))" >> $GITHUB_OUTPUT

        # Upload the full release of Blender Add-on
        - name: Upload Blender Addon
          uses: actions/upload-artifact@v4
          with:
            name: lipsync-addon
            path: ${{ steps.get-zip.outputs.ZIP_NAME }}