name: Simple Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build-extension:
      name: Blender Extension Build
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Install Blender via Snap
          run: sudo snap install blender --classic

        - name: Build Extension with blender
          run: blender --command extension build --split-platforms

          # Not used for now but will be used when automating releases
#        - name: Get generated zip filenames
#          id: get-zips
#          run: |
#            ZIP_NAMES=$(ls ./*.zip | tr '\n' ' ')
#            echo "ZIP_NAMES=$ZIP_NAMES" >> $GITHUB_OUTPUT

        # Upload the full release of Blender Add-on
        - name: Clean platform-specific archives
          run: |
            for zipfile in iocgpoly_lip_sync-*-*.zip; do
              echo "Examining $zipfile"
              unzip -l "$zipfile" | grep -i "archives"

              # Extract platform from filename (between last - and _)
              platform=$(echo $zipfile | sed 's/.*-\(.*\)_.*/\1/')

              echo "Processing $zipfile (platform: $platform)"

              # Create temp dir
              temp_dir="${platform}_temp"
              unzip -q "$zipfile" -d "$temp_dir"

              # List the actual directory structure
              echo "Directory structure in temp_dir:"
              ls -la "$temp_dir/Assets/Archives/"

              rm "$zipfile"
              cd "$temp_dir"

              # Remove irrelevant platform folders based on the platform
              case $platform in
                linux)
                  rm -rf Assets/Archives/darwin Assets/Archives/windows
                  ;;
                macos)
                  rm -rf Assets/Archives/linux Assets/Archives/windows
                  ;;
                windows)
                  rm -rf Assets/Archives/darwin Assets/Archives/linux
                  ;;
              esac

              # List what remains
              echo "Remaining directories:"
              ls -la Assets/Archives/

              # Rezip with same name
              zip -r "../$zipfile" .
              cd ..
              rm -rf "$temp_dir"
            done

        - name: Upload Blender Addon
          uses: actions/upload-artifact@v4
          with:
            name: extension-builds
            path: ./*.zip

  automatic-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    name: Automatic Release
    runs-on: ubuntu-latest

    steps:
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
        
